name: build for test automation
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          ref: refs/heads/master
      - name: install
        run: |
          npm install cypress
      - name: uat
        run: |
          npx cypress run --spec "cypress/integration/examples/Test12.spec.js"
