name: build for test automation
on: [push]
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
        with:
          ref: refs/heads/main
      - name: install
        run: |
          npm install cypress
      - name: Run Test
        run: |
          npx cypress run --spec "cypress/integration/examples/Test12.spec.js"
